### ISSUE TITLE
Invalid Syntax Error When Running Main.py

### ISSUE THREAD

**Issue by yakaboskic** [tirthajyoti/Design-of-experiment-Python#1]
I was running Main.py using python 3.5 and received an syntax error from print command. Make sure to run the DoE code with python 3.6 because apparently the print syntax changed from 3.5 to 3.6.

**Comment by tirthajyoti** [comment]
Thank you @yakaboskic for mentioning this. 
I will make those print statements more general in the next iteration.

BTW, a standalone Python package **`doepy`** has been released as Alpha 0.0.1 version. 
You can install using `pip install doepy` and start using.

[Read the docs here](https://doepy.readthedocs.io/en/latest/).

Closing this issue now.
